name: Test & Build

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          key: clj-${{ github.repository }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ github.repository }}-
          path: |
            ~/.gitlibs
            ~/.m2/repository

      - name: Set version
        run: |
          echo "HYPERFIDDLE_ELECTRIC_APP_VERSION=`git describe --tags --long --always --dirty`" >> $GITHUB_ENV

      - name: Build
        run: |
          nix develop -c clojure -X:build uberjar :jar-name target/biobricks-web-"$HYPERFIDDLE_ELECTRIC_APP_VERSION".jar :version '"'$HYPERFIDDLE_ELECTRIC_APP_VERSION'"'
